EnterpriseDB/edb-terraform

README.md, edbterraform/data/templates/aws/network.tf.j2, edbterraform/data/terraform/aws/modules/security/main.tf
Open ports for region's subnet cidr blocks
* Open ports by region with `region_ports` option to reduce exposure for services needed by machines in the same region
* `service_ports` opens the ports to any ip currently
=> Open ports to region's subnets

edbterraform/data/terraform/aws/modules/aurora/main.tf, edbterraform/data/terraform/aws/modules/database/main.tf
Add another keyword to the names for subnet groups and database parameters so that tests on Aurora and RDS do not clash in names.
=> Add differentiators to some resource names

README.md, edbterraform/data/templates/gcloud/alloy.tf.j2, edbterraform/data/templates/gcloud/database.tf.j2, edbterraform/data/templates/gcloud/main.tf.j2, edbterraform/data/templates/gcloud/network.tf.j2, edbterraform/data/templates/gcloud/providers.tf.j2, edbterraform/data/templates/gcloud/region_peering.tf.j2, edbterraform/data/terraform/gcloud/modules/alloy/main.tf, edbterraform/data/terraform/gcloud/modules/alloy/outputs.tf, edbterraform/data/terraform/gcloud/modules/alloy/providers.tf, edbterraform/data/terraform/gcloud/modules/alloy/variables.tf, edbterraform/data/terraform/gcloud/modules/database/outputs.tf, edbterraform/data/terraform/gcloud/modules/machine/outputs.tf, edbterraform/data/terraform/gcloud/variables.tf, edbterraform/lib.py, infrastructure-examples/alloy.yml, infrastructure-examples/gcloud-all.yml
AlloyDB:
* uses `google-beta` provider
* database name not configurable through terraform
* ports not configurable
* database version not configurable, inferred by final configuration
* currently postgres 14 compatable
* private network only and peered to same regions VPC with no public access option
* create bastion host in the same region or use alternative connection method
Template changes:
* `main.tf.j2` 
* removal of jinja2 check for locals and instead initial variable defined in `variable.tf`
* outputs modified
* able to use `terraform output -json`
Fixes:
* region peering race condition
* allow cloudsql and alloydb to be created without zones defined for its region
=> Gcloud AlloyDB support

edbterraform/data/terraform/aws/modules/database/main.tf
Depending on the database engine, the configuration group family format can be `dbengine-version` or `dbengineversion`.
With this fix, Oracle database provisioning in RDS is supported.
Note: using the db.t3.micro instance type is not allowed with oracle-ee. Tests with db.t3.large worked.
Infrastructure file sample:
```yaml
databases:
mydb1:
engine: oracle-ee
engine_version: 19
instance_type: db.t3.large
port: 1521
```
=> RDS: fix configuration group family name

edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, edbterraform/lib.py
Changes:
* `count` supported in specification module for machines under each provider
* creates a list of objects for the amount of count and adds an index to its name to avoid modifying each provider's machine module with terraform's `count`
* If not used by the user, it will default to 1
* users should add a tag instead of relying on the name of the machine
* we have `type` in outputs, but we should favor having users define `type` as a tag as those are output in `servers.yml` as well.
=> Support for `count` in each provider's spec

edbterraform/__main__.py, edbterraform/lib.py, setup.py
Allow for more entry points to test changes without needing to reinstall each time:
* testing local changes without `setup.py` while current-working-directory is `edb-terraform`: `python -m edbterraform`
* testing local code changes from any directory: `python edbterraform/edb-terraform`
* system python package after `setup.py`: `edb-terraform`
* system python module after `setup.py`: `python -m edbterraform`
Changes:
* dunder main `__main__.py` added to handle entry point
* setup.py `entry_point` points to `edbterraform.__main__:main`
=> Dunder main entry point

edbterraform/data/templates/aws/main.tf.j2, edbterraform/data/templates/azure/main.tf.j2, edbterraform/data/templates/gcloud/main.tf.j2, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, edbterraform/lib.py
Changes:
* terraform root level output updated to better match `servers.yml` for direct use
* `terraform output -json | python -m json.tool`
* `terraform output -json servers | python -m json.tool`
* `servers` output put in a variable, passed to jinja and user given a message of how to use it
* Specification module for all providers: machines `type` optional as user can pass it as a `tag` and reference it from the outputs with their own conditional checks.
=> terraform output updated for direct use

edbterraform/__main__.py, setup.py
When using setup tools, it uses the entry_point directly: `sys.exit(entry_point)`. If the entry_point returns anything but 0, it will cause scripts to error out. In our case, it return `servers` from `main()` so an `entry_point()` was made to call `main()` so scripts do not error out.
=> entry_point bug fix

edbterraform/data/terraform/azure/modules/security/main.tf, infrastructure-examples/azure-vms.yml
`title()` used with protocol name since the provider expects the starting character to be uppercase.
=> Azure provider protocol name handling

edbterraform/data/terraform/aws/modules/machine/outputs.tf, edbterraform/data/terraform/azure/modules/machine/outputs.tf, edbterraform/data/terraform/gcloud/modules/machine/outputs.tf
`additional_volumes` is passed through so user can further modify their volumes if needed. We make the initial mount point tied to the `UUID` set during the filesystem formatting and add it to `/etc/fstab` so that it can be tracked. 
This is needed due to differences in how the providers handle device names and mounting order.
When volumes are modified, the user should take care to track the new `uuid`, or use an alternative method, and modify `/etc/fstab` accordingly.
=> `additional_volumes` added to each provider's machine outputs

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/providers.tf, edbterraform/data/terraform/aws/modules/machine/setup_volume.sh, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/machine/setup_volume.sh, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/machine/setup_volume.sh, edbterraform/data/terraform/gcloud/modules/machine/variables.tf
Changes:
* AWS volume script updated to allow fallback to device name instead of `nvme` tool
* Device is still mounted with its `UUID` inside of `/etc/fstab`
* Users need to update `/etc/fstab` if they reformat the device
* GCloud and Azure updated to match where possible
=> Volume script device name fallback

edbterraform/data/templates/aws/machine.tf.j2, edbterraform/data/templates/aws/main.tf.j2, edbterraform/data/templates/aws/network.tf.j2, edbterraform/data/templates/azure/main.tf.j2, edbterraform/data/templates/azure/network.tf.j2, edbterraform/data/templates/gcloud/main.tf.j2, edbterraform/data/templates/gcloud/network.tf.j2, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/outputs.tf, edbterraform/data/terraform/aws/modules/security/providers.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/security/main.tf, edbterraform/data/terraform/azure/modules/security/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/security/main.tf, edbterraform/data/terraform/gcloud/modules/security/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Allow user to specify list of cidrs under each defined `region_ports` and `service_ports`:
* `ingress_cidrs` available: list of strings that represent a cidr range
* `service_ports` defaults to `["0.0.0.0/0"]`
* `egress_cidrs` available: list of strings that represent a cidr range
* `service_ports` and `region_ports` defaults to `region_cidrblocks` if not defined
* `region_cidrblocks` specification output is a list of cidrs of from all regions
* `region_ports` specification output is a mapping of region name to a list of service and region ports
* `spec` output available through the root module for inspection
Reference: Organizations can block `0.0.0.0/0` from direct use.
=> Allow modified CIDR ranges

edbterraform/data/templates/aws/main.tf.j2, edbterraform/data/templates/azure/main.tf.j2, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/outputs.tf
Fixes:
* AWS default egress for outbound access set in firewall rules
* AWS icmp fix
* `sensitive=true` was re-added if missing from `main.tf.j2`
PR: https://github.com/EnterpriseDB/edb-terraform/pull/34
=> AWS egress default and spec output fix

edbterraform/data/templates/aws/machine.tf.j2, edbterraform/data/templates/aws/network.tf.j2, edbterraform/data/templates/azure/machine.tf.j2, edbterraform/data/templates/azure/network.tf.j2, edbterraform/data/templates/gcloud/kubernetes.tf.j2, edbterraform/data/templates/gcloud/machine.tf.j2, edbterraform/data/templates/gcloud/network.tf.j2, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/aws/modules/validation/main.tf, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/network/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/main.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, edbterraform/lib.py, infrastructure-examples/aws-ec2-v2.yml, infrastructure-examples/azure-vms-v2.yml, infrastructure-examples/compute-engine-v2.yml
* To support multiple defined zones of the same zone within a region, we move from a mapping of strings, `optional(map(string))`, to a mapping of objects, `optional(map(object({zone = string, cidr = string})))`.
* Machines and google kubernetes can reference their desired zone by using `zone_name` to reference one of the defined `zones`
* Backwards compatibility added
=> Region zone mappings

edbterraform/data/terraform/aws/variables.tf, edbterraform/lib.py, edbterraform/utils/files.py
Use `safe_load` instead of using `CLoader`, which depends on `libyaml` and might require a manual install with the use of `python setup.py --with-libyaml install` when using python virtual environments.
When manual install is skipped, the virtual environment might fail to detect `libyaml`, `CLoader` is then not available within `PyYAML` and fails with an `ImportError` if `CLoader` is imported.
Error message - `ERROR: could not read file /home/user/Projects/edb-terraform/infrastructure-examples/aws-all.yml (module 'yaml' has no attribute 'CLoader')`
Ref: https://github.com/yaml/pyyaml/issues/108
Other Changes:
* Removed unused `security_group_ids` variable from AWS modules root variable file
* added `ImportError` to `try/except` import
=> Fix: use of PyYAML 'safe_load' instead of 'CLoader'

edbterraform/data/templates/aws/machine.tf.j2, edbterraform/data/terraform/aws/modules/aurora/main.tf, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/network/main.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf
Issue:
AWS quota limit hit when using too many security groups
PR: https://github.com/EnterpriseDB/edb-terraform/pull/34
Causes:
VPC Security Group limit per instance
VPC security Groups limit per elastic network interface
Ref: https://repost.aws/questions/QUragGhbTXSqSKO4B1zIJUGw/quot-exceeded-quot-vpc-security-groups-limit-when-launching-instances-with-one-sg
Fix:
Use `aws_security_group_rules` with pre-set `aws_security_group`'s.
This is also a workaround for the issue where an `aws_instance` is force recreated when a security group is added or removed.
Other Fixes:
* `subnet_id` grabbed from the network module since the data source output forces `aws_resource` to be re-created
* ignore `ami` output changes as it forces `aws_instance` to be recreated
* `cluster_identifier_prefix`, …
=> Fix: AWS security group limits

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf
AWS Changes:
* machines can now define `ports` to define custom security groups
* `skip_ssh_check` removed and associated validation check. It will now fail after creating the machine but before creating additional volumes so that volumes are not left in an unformatted state. If ssh is needed after a failed run, such as for machines with additional volumes, machines can add needed port rules and `terraform apply` can be re-run to continue provisioning resources.
* machines can now define `ssh_port` to define the default ssh port otherwise `22` is used.
AWS Fixes:
* machines create implicit dependencies instead of using `depends_on` as it can run out of order after initial runs. This is done with the use of variables and lifecycles.
* Handle duplicate security rules when using …
=> Allow AWS ports to be defined by machine

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, infrastructure-examples/aws-all.yml, infrastructure-examples/aws-ec2-v2.yml
AWS security rules should be defined with `type` to allow control of ingress and egress since we no longer define security rules as groups but a set of rules within a security group.
Changes:
* AWS: each port rule can use `type` to define connection direction, defaults to `ingress`.
* AWS: `ingress_cidrs`/`egress_cidrs` replaced with `cidrs`.
* AWS: machines create an egress port rule for outbound access if no egress port is defined.
* AWS: infrastructure examples updated
=> Update AWS security rules

edbterraform/data/terraform/aws/modules/specification/variables.tf
Issue:
Image owner is defined as `owner: 099720109477` but `0` is dropped as shown in the following error message.
`Error: reading EC2 AMIs: InvalidUserID.Malformed: Invalid user id: "99720109477"`
Cause:
owner is of type `number`
Fix:
`owner` in specification changed to type `string`
Ref: https://github.com/EnterpriseDB/edb-terraform/pull/22
=> Fix: AWS image owners type

edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Messed up the branches:
https://github.com/EnterpriseDB/edb-terraform/pull/51
https://github.com/EnterpriseDB/edb-terraform/pull/52
=> Fix: allow public access of gcloud-sql

README.md, edbterraform/data/templates/azure/database.tf.j2, edbterraform/data/templates/azure/machine.tf.j2, edbterraform/data/templates/azure/main.tf.j2, edbterraform/data/terraform/azure/modules/database/main.tf, edbterraform/data/terraform/azure/modules/database/outputs.tf, edbterraform/data/terraform/azure/modules/database/providers.tf, edbterraform/data/terraform/azure/modules/database/variables.tf, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, infrastructure-examples/azure-database.yml
Support for Azure PostgreSQL Database on Flexible Server
* Firewall allows for all azure internal services to connect, including virtual machines and non-owned virtual machines within the azure network
* `public_access` can be used to open the firewall to all traffic outside of azure's network
* README update
* Example placed under `infrastructure-examples/azure-database.yml`
```yaml
---
azure:
tags:
cluster_name: flexible-server
created_by: edb-terraform
regions:
westus:
cidr_block: 10.2.0.0/16
databases:
postgres:
region: westus
engine: postgresql
engine_version: 14
username: postgres
password: asdfavu899fnvoabnsviob
instance_type: GP_Standard_D4s_v3
volume:
size_gb: 32
tags:
environment: Sandbox
type: postgres
```
Fix: Azure linux machines would fail to decode data source's public key.
=> Azure postgres database on flexible server support

edbterraform/data/templates/aws/network.tf.j2, edbterraform/data/templates/aws/region_peering.tf.j2, edbterraform/data/templates/azure/network.tf.j2, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/network/main.tf, edbterraform/data/terraform/aws/modules/routes/main.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/main.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/aws/modules/vpc/main.tf, edbterraform/data/terraform/aws/modules/vpc_peering/main.tf, edbterraform/data/terraform/aws/modules/vpc_peering_accepter/main.tf, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/security/main.tf, edbterraform/data/terraform/azure/modules/security/variables.tf, edbterraform/data/terraform/azure/modules/specification/main.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/vpc/main.tf, edbterraform/data/terraform/azure/modules/vpc/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/service_connection/main.tf, edbterraform/data/terraform/gcloud/modules/specification/main.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Tags updated for all providers.
Top-level tag changed to `map(str)` to allow for additional top level tags instead of filtering them out. Since they are used across all resources, there could be issues due to account restrictions or quotas.
* `cluster_name` - required top level tag
* `created_by` - required top level tag
* `terraform_id` - generated from random during initial terraform run
* `terraform_hex` - generated from random during initial terraform run
* `terraform_time` - timestamp generated during initial terraform run
** to avoid errors, gcloud generated outputs are modified to match label restrictions
=> resource tags updated across all providers

edbterraform/data/terraform/gcloud/modules/machine/main.tf
Stop gcloud from re-creating the machines so we can add additional machines as needed. We can still add additional volumes, but we cannot change the image or boot device, which matches AWS. A new resource can be created instead and configured as needed.
Azure is not experiencing the same problem as AWS/Gcloud.
=> Fix: Gcloud machine dependencies

edbterraform/data/templates/aws/network.tf.j2, edbterraform/data/templates/aws/region_peering.tf.j2, edbterraform/data/templates/azure/network.tf.j2, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
PR-https://github.com/EnterpriseDB/edb-terraform/pull/56 broke old workflows as it enforced `cluster_name` and `created_by` tags. Validation check was removed and updated templates to use outputs and not the specification variable directly.
Related error:
```
+ terraform apply -auto-approve
╷
│ Error: Invalid value for variable
│
│   on main.tf line 10, in module "spec":
│   10:   spec = var.spec
│     ├────────────────
│     │ var.spec.tags is map of string with 1 element
│     │ var.spec.tags.cluster_name is "TPCC-refdata"
│
│ cluster_name and created_by need to be defined under tags
│ Tags: {"cluster_name":"TPCC-refdata"}
│
│ This was checked by the validation rule at
│ modules/specification/variables.tf:132,3-13.
```
=> Fix: tags regression from PR-56

README.md, edbterraform/CLI.py, edbterraform/Logger.py, edbterraform/__init__.py, edbterraform/__main__.py, edbterraform/args.py, edbterraform/lib.py
Support for new commands:
* depreciated - generate terraform files with positional arguments (default)
* setup - installs terraform
* generate - generates a terraform files based on an yaml infrastructure file 
---
* Default behavior: In order to avoid breaking old calls, the following syntax is still valid: `edb-terraform PROJECT_PATH INFRA_FILE_YAML`
* `-h` - help will display the new available commands
* `edb-terraform depreciated -h` - display help for depreciated call
* `edb-terraform setup`
* installs a valid terraform binary inside of `~/.edb-terraform/bin` by default
* short description added
* `edb-terraform generate`
* generate terraform files based on a yaml infrastructure file
* short description added
* Any commands with defaults will be exposed as environment variables. User …
=> `generate` and `setup` commands

edbterraform/args.py, requirements.txt, setup.py
* built-in types are not supported until `python3.9`
* built-in dataclasses are not supported until `python3.7`
* added `requirements.txt` and used in `setup.py`
Ref: https://github.com/EnterpriseDB/edb-terraform/pull/55
=> fix: python compatibility for `types` and `dataclasses`

edbterraform/lib.py
```sh
+++ dirname -- ./run.sh
++ cd -- .
++ pwd
+ SCRIPT_DIR=/var/lib/buildbot-worker/rundir/AWS_HammerDB_TPROC-C_EC2_EPAS_Oracle_Compability/build/14/aws-hammerdb-epas-oracle-compatibility/00_provision
+ edb-terraform /var/lib/buildbot-worker/rundir/AWS_HammerDB_TPROC-C_EC2_EPAS_Oracle_Compability/build/14/terraform /var/lib/buildbot-worker/rundir/AWS_HammerDB_TPROC-C_EC2_EPAS_Oracle_Compability/build/14/aws-hammerdb-epas-oracle-compatibility/00_provision/../infrastructure.yml
Traceback (most recent call last):
File "/var/lib/buildbot-worker/venv/bin/edb-terraform", line 11, in <module>
load_entry_point('edb-terraform==1.3.0', 'console_scripts', 'edb-terraform')()
File "/var/lib/buildbot-worker/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point …
```
=> Fix: type causing error in python3.8 <=

edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Issue:
Security module for `AWS` is failing when port description is omitted by the user.
Error message:
```terraform
╷
│ Error: Error in function call
│ 
│   on modules/security/variables.tf line 30, in locals:
│   30:       => coalesce(port.description, "")...
│     ├────────────────
│     │ port.description is null
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
╵
```
Fix:
Default, non-empty string provided in `coalesce` function to handle case where module is given a port with no description. 
AWS/Azure/Gcloud specification module's port descriptions updated with a default to match.
=> Fix: AWS security module fails due to empty string

edbterraform/data/terraform/gcloud/modules/alloy/main.tf, edbterraform/data/terraform/gcloud/modules/alloy/outputs.tf, edbterraform/data/terraform/gcloud/modules/alloy/variables.tf, edbterraform/data/terraform/gcloud/modules/database/main.tf, edbterraform/data/terraform/gcloud/modules/database/outputs.tf, edbterraform/data/terraform/gcloud/modules/database/variables.tf, edbterraform/data/terraform/gcloud/modules/kubernetes/main.tf, edbterraform/data/terraform/gcloud/modules/kubernetes/outputs.tf, edbterraform/data/terraform/gcloud/modules/kubernetes/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/machine/outputs.tf, edbterraform/data/terraform/gcloud/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf
Issue: 
PR https://github.com/EnterpriseDB/edb-terraform/pull/56 , modified the tags with lower and replace before passing them through to the outputs for gcloud but this was not needed for azure and aws. This now means the tags might vary between outputs and users might face issues when creating templates based on expected tags or need additional error handling within their templates, PR: https://github.com/EnterpriseDB/edb-terraform/pull/64 .
Fix: 
Gcloud tags passed through in the tags outputs to match the rest of the providers. Since gcloud requires specific structure and uses the term `labels` instead of `tags`, so it will have an output for labels instead.
Terraform servers.yml file output:
```terraform
labels: {"cluster_name":"gcloud-infra","created_by":"edb-terraform-gcloud","name" …
```
=> Fix: Update Gcloud to match Azure/AWS tags output

edbterraform/data/templates/azure/machine.tf.j2, edbterraform/data/templates/azure/network.tf.j2, edbterraform/data/templates/gcloud/machine.tf.j2, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/network/main.tf, edbterraform/data/terraform/azure/modules/network/outputs.tf, edbterraform/data/terraform/azure/modules/network/variables.tf, edbterraform/data/terraform/azure/modules/security/main.tf, edbterraform/data/terraform/azure/modules/security/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/security/main.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, infrastructure-examples/aws-ec2-v2.yml, infrastructure-examples/azure-vms-v2.yml, infrastructure-examples/compute-engine-v2.yml
Allow for port ranges to be defined with an optional `to_port` key, under any port rule.
* Azure/Gcloud can define an optional `access` key and set it to `allow` (default) or `deny`.
* This is not set for AWS as its security groups grant access but cannot deny access.
Fixes:
* GCloud spec updated to allow machine specific port rules, mimicking AWS security groups 
* Requires unique naming within security module
* GCloud implicit dependencies updated for volume scripts
* Azure spec updated to allow machine specific port rules, mimicking AWS security groups
* Each service/region port rule added to a machine if it has additional port rules so that a network interface security group can be used instead of the default security group
* avoids conflicting priorities as each interface will have …
=> AWS/Azure/GCloud: Allow port ranges and per machine rules

edbterraform/args.py, edbterraform/lib.py
To help with reproducing and confirming environments, the following changes were made:
* original infrastructure file input will be copied to `<project directory>/infrastructure.yml.bak`
* `edb-terraform.version` key appended to the end of the yaml file
* terraform hcl lock file can be supplied with `edb-terraform generate`. This is needed to lock provider packages during `terraform init`.
```
--lock-hcl-file LOCK_HCL_FILE
Terraform Lock HCL file is used to ensure the same package versions are used across architectures with terraform's cli. If not
used, terraform will try to grab the latest versions from each provider. Default: None | Default Environment variable:
ET_LOCK_HCL_FILE
```
Ref: https://github.com/EnterpriseDB/edb-benchmarks/pull/76
=> edb-terraform cli additional saved data

README.md, edbterraform/data/terraform/aws/modules/biganimal/variables.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf
Fixes:
* BigAnimal: aws - modules referenced wrong provider, `azure`, instead of `aws`
* BigAnimal: aws/azure - `cluster_name` references local, instead of variable, since it may be omitted in configuration files.
=> Biganimal fixes

edbterraform/data/terraform/aws/modules/aurora/outputs.tf, edbterraform/data/terraform/aws/modules/database/outputs.tf, edbterraform/data/terraform/aws/modules/machine/outputs.tf
Updated `outputs.tf ` to get the instance and/or cluster ids for aurora, rds (database), and ec2 (machines).
=> Get aws, rds, ec2 instance ids, cluster ids from outputs

edbterraform/data/terraform/aws/modules/database/outputs.tf
Changed one variable in outputs.tf to make this functional with aws-dbt2-rds metric-stats updates.
=> Add instance id for aws-dbt2-rds

edbterraform/CLI.py, edbterraform/args.py, edbterraform/lib.py
New options added to `edb-terraform generate` allow a user to destroy a project as well as being able to apply after generating the terraform project:
* `--destroy` - attempt to destroy resources before creating a new project
* `--apply` - attempt to create resources with `terraform apply`
Terraform plan created with the filename `terraform.plan` under the project when using `--apply` or `--run-validation`.
=> allow creation or destroying of resources while generating a project

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/setup_volume.sh, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf
Make xfs the default filesystem but make it a variable instead of hard coding it.  This is in preparation of being able to handle raw volumes for software volume management.
As a side effect we could also set different file system other than xfs.
=> aws: refactor file system handling

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, infrastructure-examples/aws/machines-v2.yml
The infrastructure template now allows spot_max_price to be defined per AWS machine for the maximum hourly price.  Omitting this value continue previous behavior where an on-demand price will be used for an on-demand instance.
=> support requesting persistent spot instances

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/setup_volume.sh, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, infrastructure-examples/aws/all.yml
Example:
additional_volumes:
- mount_point: /opt/pg_data size_gb: 20 type: io2 iops: 5000 encrypted: false filesystem: "xfs" filesystemmountopt: "noatime,nodiratime"
=> Use filesystemmountopt for custom mount options

edbterraform/CLI.py
Version Bump to v1.5.5:
** *2023 August 10th: HashiCorp changed the Terraform license from MPL to BSL/BUSL-1.1*
- [HashiCorp Licensing](https://www.hashicorp.com/bsl)
- [BSL License Change Commit](https://github.com/hashicorp/terraform/commit/b145fbcaadf0fa7d0e7040eac641d9aef2a26433)
- [Terraform v1.5.5](https://github.com/hashicorp/terraform/releases/tag/v1.5.5)
- [Last MPL Licensed Commit](https://github.com/hashicorp/terraform/tree/8a085b427b74ce3829500a59508b77465f1bbef0)
Full list from the [forum discussion](https://discuss.hashicorp.com/t/hashicorp-projects-changing-license-to-business-source-license-v1-1/57106):
- [Terraform](https://github.com/hashicorp/terraform) - BSL
- [Vagrant](https://github.com/hashicorp/vagrant) - BSL
- [Packer](https://github.com/hashicorp/packer) - BSL
- …
=> Terraform CLI - version bump to v1.5.5

edbterraform/data/templates/aws/biganimal.tf.j2, edbterraform/data/templates/azure/biganimal.tf.j2, edbterraform/data/templates/gcloud/biganimal.tf.j2, edbterraform/data/terraform/aws/modules/biganimal/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/biganimal/variables.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/biganimal/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, infrastructure-examples/aws/biganimal.yml, infrastructure-examples/azure/biganimal.yml, infrastructure-examples/gcloud/biganimal.yml
We can allow the use of biganimal hosted resources instead of using your own cloud account.
`bah` must be appended to the `cloud_provider` name:
Ref: https://github.com/EnterpriseDB/terraform-provider-biganimal/discussions/309
`cloud_account` (`true` by default) can be set under biganimal configurations. To use biganimal hosted resources, `cloud_account` should be set to `false`.
=> Allow for biganimal hosted resources

edbterraform/CLI.py, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/machine/variables.tf, infrastructure-examples/aws/all.yml, infrastructure-examples/aws/edb-ra-3.yml, infrastructure-examples/aws/machines-v2.yml, infrastructure-examples/aws/machines.yml, infrastructure-examples/azure/machines.yml, infrastructure-examples/gcloud/all.yml, infrastructure-examples/gcloud/alloy.yml, infrastructure-examples/gcloud/biganimal.yml, infrastructure-examples/gcloud/cloudsql.yml, infrastructure-examples/gcloud/machines-v2.yml, infrastructure-examples/gcloud/machines.yml
Handle GCP regex restriction when using a machine key that contains an underscore:
* Regex restriction:
* `^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$` 
* Resources:
* `google_compute_address`
* `google_compute_instance`
This is needed to allow referencing of variables with dot notation instead of brackets or escaped strings when using `terraform`, `ansible` and `jq`.
=> GCP machine keyname handling

edbterraform/data/terraform/aws/modules/biganimal/main.tf, edbterraform/data/terraform/aws/modules/biganimal/variables.tf, edbterraform/data/terraform/azure/modules/biganimal/main.tf, edbterraform/data/terraform/azure/modules/biganimal/variables.tf, edbterraform/data/terraform/gcloud/modules/biganimal/main.tf
Omitted backup retention period causes provisioning to fail with biganimal provider `v0.6.0`.
Issue: https://github.com/EnterpriseDB/terraform-provider-biganimal/issues/322
Fix be apart of `v0.6.1` release next week.
We need the minimum retention period so we will set it to `1d`.
PR: https://github.com/EnterpriseDB/edb-terraform/pull/84
Commit: 2f6660901230e73e0617f2c28d6a9316d8e5a7fc
```
+ resource "biganimal_cluster" "instance" {
+ backup_retention_period       = "1d"
+ cloud_provider                = "bah:gcp"
+ cluster_id                    = (known after apply)
+ cluster_name                  = (known after apply)
+ cluster_type                  = (known after apply)
+ connection_uri                = (known after apply)
+ created_at                    = (known after apply)
+ csp_auth …
```
=> Biganimal retention updated to `1d`

README.md, edbterraform/data/terraform/aws/modules/machine/lsblk_devices.sh, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/outputs.tf, edbterraform/data/terraform/aws/modules/machine/providers.tf, edbterraform/data/terraform/aws/modules/machine/setup_volume.sh, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/machine/lsblk_devices.sh, edbterraform/data/terraform/azure/modules/machine/main.tf, edbterraform/data/terraform/azure/modules/machine/outputs.tf, edbterraform/data/terraform/azure/modules/machine/providers.tf, edbterraform/data/terraform/azure/modules/machine/setup_volume.sh, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/lsblk_devices.sh, edbterraform/data/terraform/gcloud/modules/machine/main.tf, edbterraform/data/terraform/gcloud/modules/machine/outputs.tf, edbterraform/data/terraform/gcloud/modules/machine/providers.tf, edbterraform/data/terraform/gcloud/modules/machine/setup_volume.sh, edbterraform/data/terraform/gcloud/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, setup.py
Refactor how volumes are setup so that we can later handle filesystems such as LVM:
* Use of `toolbox_external` instead of provisioners:
* Return values back into terraform state
1. after machine creation
2. after addtional volumes are attached
3. after volumes are formatted.
* Setup volume script copied once and run once after it has a view of all available resources
* Implicit dependencies set in query parameter but unused
* `block_devices` output available for AWS, Azure, and GCP virtual machines.
* 3 map values
* `initial` - block devices after creation/first start.
* `all` - block devices after attaching all volumes
* `final` - block devices after formatting
resolves https://github.com/EnterpriseDB/edb-terraform/issues/30
closes https://github.com/EnterpriseDB/edb-terraform/pull/40 …
=> Volume refactor

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, infrastructure-examples/aws/machines-v2.yml
`jbod_volumes` option added to allow creation of volumes alongside a machine while skipping the attachment and formatting of the volume.
For management, use the `arn` and `id` set under the `jbod_volumes` for each machine's output.
example usage under a machine configuration:
```yaml
jbod_volumes:
0:
type: gp2
size_gb: 100
encrypted: false
1:
type: gp3
size_gb: 100
encrypted: false
throughput: 300
iops: 300
```
=> aws machine module: just a bunch of volumes disk management

edbterraform/data/terraform/aws/modules/biganimal/variables.tf, edbterraform/data/terraform/azure/modules/biganimal/variables.tf, edbterraform/data/terraform/gcloud/modules/biganimal/variables.tf
`nullable` should be set to `false` so that the default is used when `null` is passed in.
Original PR: https://github.com/EnterpriseDB/edb-terraform/pull/97
=> Biganimal cloud_account `nullable` fix

edbterraform/data/templates/aws/main.tf.j2, edbterraform/data/terraform/aws/modules/aurora/outputs.tf, edbterraform/data/terraform/aws/modules/biganimal/main.tf, edbterraform/data/terraform/aws/modules/biganimal/outputs.tf, edbterraform/data/terraform/aws/modules/biganimal/providers.tf, edbterraform/data/terraform/aws/modules/biganimal/variables.tf, edbterraform/data/terraform/aws/modules/database/outputs.tf, edbterraform/data/terraform/aws/modules/machine/outputs.tf, edbterraform/data/terraform/aws/modules/vpc_peering_accepter/main.tf
* VPC Peering tags fix
* Additional BigAnimal outputs added which are needed for vpc peering or vpc endpoints
* `vpc_id`
* `vpc_name`
* `biganimal_id`
* `loadbalancer.name`
* `loadbalancer.dns`
* `resources` output added to modules to easily reference any child resource name and all available attributes. While we could use `terraform.tfstate` to find some of this information, local access will be lost with a remote state and it is grouped as a list of resources and not by the parent module:
* For example:
`terraform.tfstate`
```json
{
"resources" : [
{
"module": "module.biganimal_us_east_2[\"mydb2\"]",
"mode": "managed",
"type": "biganimal_cluster",
"name": "instance",
"instances": [ ... ],
...
}
]
}
```
`terraform output -json servers | jq .`
```json
{
"biganimal": {
"mydb2": { …
```
=> AWS Module updates

edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/setup_volume.sh, edbterraform/data/terraform/aws/modules/specification/variables.tf, infrastructure-examples/aws/machines-v2.yml
Allow for creation and formatting of volumes with LVM2. To start, this will assume a striping across all the `volume_group`'s devices.
A new option under `additional_volumes` was added, `volume_group`, to set which volume group it belongs to.
When using `volume_group`, use the `volume_groups` mapping with the `volume_group` as the first key followed by `mount_point` as a nested key to setup logical volumes, filesystem and mounting through `/etc/fstab`.
Example configuration:
```yaml
additional_volumes:
- size_gb: 20
type: gp2
iops: 5000
encrypted: false
volume_group: data
- size_gb: 20
type: gp2
iops: 5000
encrypted: false
volume_group: other
- mount_point: /opt/test
size_gb: 20
type: gp2
iops: 5000
encrypted: false
filesystem: xfs
- size_gb: 20
type: gp2
iops: 5000
encrypted: false …
```
=> LVM volumes

edbterraform/CLI.py, edbterraform/args.py, edbterraform/lib.py, edbterraform/utils/logs.py, edbterraform/utils/script.py
Changes:
* `--help` overrides all command options
* `version` can be passed as a command or as an argument `-v`/`--version`
* `--no-console-log` can be set to pass logs to a file instead of the console
* Cloud CLIs can be installed with `edb-terraform setup`
* Aws - pip installation of git releases since v2 is not released to `pypi`, only v1
* Azure - pip releases available
* Gcloud - bundle python packages from google archives
* BigAnimal - binary available for download and get-token.sh from git
=> Cloud CLIs

setup.py
Issue:
Setuptools leaves behind build artifacts instead of cleaning them up. This can cause unexpected errors due to old build artifacts being re-used.
Solution:
Use a context manager to setup a directory with all the source code and set the `setup()` context. The context manager handles removal of the directory when the process finishes.
This might need to be updated if we move to different types of releases, such as pipy, but at the moment we use `pip install` from the source directory or directly from github with `git` or `zip`.
- While we can use `cmdclass` to override some of the behavior of `setuptools`, it requires class overrides and setuptools handles the execution.
- `atexit` can be used to setup a function to cleanup directories but it is a blind removal based on directory name …
=> setuptools context

setup.py
Reverts EnterpriseDB/edb-terraform#124
```shell
$ edb-terraform generate --project-name terraform -c aws --infra-file docs/examples/aws/machines-v2.yml --destroy
2024-02-15T21:34:59+0000 - edb-terraform - INFO - path does not exist yet, no destruction needed
2024-02-15T21:34:59+0000 - edb-terraform - INFO - Copy templates from /home/user/.local/lib/python3.10/site-packages/edbterraform/data/templates/user into /home/user/.edb-terraform/templates
2024-02-15T21:34:59+0000 - edb-terraform - ERROR - ERROR: cannot create template directory /home/user/.edb-terraform/templates ([Errno 2] No such file or directory: '/home/user/.local/lib/python3.10/site-packages/edbterraform/data/templates/user')
```
=> Revert "setuptools context"

README.md, edbterraform/args.py, edbterraform/parser/hcl2.py, requirements.txt, setup.py
BREAKING CHANGE:
- python minimum version bumped to 3.8 to match cloud provider cli python minimum versions.
Changes:
- Experimental new option `help` added to display a terraform projects root level variables.
- ex: `edb-terraform help --project-path <TERRAFORM-PROJECT>`
Fix:
- Update argparse to make use of environment variables by appending it to the command if not already supplied.
- action store arguments allowed as environment variables by supplying truthy values
- ex: `--destroy` can be set as `ET_DESTROY=1`
=> `help` command for hcl2 variables

docs/examples/aws/machines-cross-region.yml, edbterraform/data/templates/aws/machine.tf.j2, edbterraform/data/templates/aws/main.tf.j2, edbterraform/data/templates/aws/validation.tf.j2, edbterraform/data/templates/azure/machine.tf.j2, edbterraform/data/templates/azure/main.tf.j2, edbterraform/data/templates/azure/validation.tf.j2, edbterraform/data/templates/gcloud/machine.tf.j2, edbterraform/data/templates/gcloud/main.tf.j2, edbterraform/data/templates/gcloud/validation.tf.j2, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/routes/main.tf, edbterraform/data/terraform/aws/modules/security/main.tf, edbterraform/data/terraform/aws/modules/security/variables.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Changes:
- Single egress security group created per VPC and used within each machine if egress is not configured.
- `force_service_machine` creates a single ssh rule at the VPC level instead of per machine
- AMI data source moved outside of the machine module which fixes issues where it tried to re-create the resource each time since the data source appeared as an unknown value.
Fixes:
- Use `aws_route` since combining it with in-line rules will cause the provider to plan to remove the routes before adding it again in the next `terraform apply`
=> AWS module updates to reduce the number of created resources

README.md, edbterraform/__init__.py, edbterraform/data/terraform/aws/modules/biganimal/main.tf, edbterraform/data/terraform/aws/modules/biganimal/providers.tf, edbterraform/data/terraform/azure/modules/biganimal/main.tf, edbterraform/data/terraform/azure/modules/biganimal/providers.tf, edbterraform/data/terraform/gcloud/modules/biganimal/main.tf, edbterraform/data/terraform/gcloud/modules/biganimal/providers.tf, edbterraform/data/terraform/versions.tf
BigAnimal now supports access keys and should be used instead of an access token.
The environment variable is `BA_ACCESS_KEY` though some of the provider docs show `EDB_TF_ACCESS_KEY` which is invalid.
=> BigAnimal Access Keys

edbterraform/__init__.py, edbterraform/data/templates/azure/machine.tf.j2, edbterraform/data/templates/gcloud/machine.tf.j2, edbterraform/data/terraform/azure/modules/machine/variables.tf, edbterraform/data/terraform/gcloud/modules/machine/variables.tf
Differs from aws machine module due to aws limitations when duplicate port rules are defined: https://github.com/EnterpriseDB/edb-terraform/pull/133
Original Commit: 3f8f635900f70dde1c12de500e4fd32acc39d89b
=> FIX Azure/Gcloud networking - re-add force_ssh_access

docs/examples/aws/machines-v2.yml, edbterraform/data/terraform/aws/modules/machine/main.tf, edbterraform/data/terraform/aws/modules/machine/setup_preattached_volumes.sh, edbterraform/data/terraform/aws/modules/machine/variables.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf
Allow formatting of preattached storage with lvm.
Use the following config under a machine definition:
```
#preattached_volumes:
```
If `preattached_volumes` is omitted or `required=false` and there is no preattached storage, it will skip any formatting to lvm.
If `mount_points` is omitted, it will skip any filesystem formatting and mounting.
=> LVM management of preattached storage

edbterraform/CLI.py
'az --version' changes the text output when an update is available and '--output json' returns text.
'az version' must be used to return a json object.
Error:
Traceback (most recent call last):
File "/home/user/.local/bin/edb-terraform", line 8, in <module>
sys.exit(entry_point())
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 24, in entry_point
main()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 17, in main
outputs = arg_parser.process_args()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/args.py", line 576, in process_args
tool.install()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/CLI.py", line 454, in install
and self.check_version().to_tuple() == …
=> edb-terraform cli - FIX - azure cli version command updated

edbterraform/CLI.py
'az --version' changes the text output when an update is available and '--output json' returns text.
'az version' must be used to return a json object.
Error:
Traceback (most recent call last):
File "/home/user/.local/bin/edb-terraform", line 8, in <module>
sys.exit(entry_point())
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 24, in entry_point
main()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 17, in main
outputs = arg_parser.process_args()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/args.py", line 576, in process_args
tool.install()
File "/home/user/.local/lib/python3.10/site-packages/edbterraform/CLI.py", line 454, in install
and self.check_version().to_tuple() == …
=> edb-terraform cli - FIX - azure cli version command updated - backport to 1.7

README.md, docs/examples/aws/biganimal.yml, edbterraform/data/templates/aws/biganimal.tf.j2, edbterraform/data/templates/aws/validation.tf.j2, edbterraform/data/templates/azure/biganimal.tf.j2, edbterraform/data/templates/azure/validation.tf.j2, edbterraform/data/templates/gcloud/biganimal.tf.j2, edbterraform/data/templates/gcloud/validation.tf.j2, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/biganimal/modules/biganimal/main.tf, edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf, edbterraform/data/terraform/common_vars.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf
Allow a custom image to be defined for biganimal clusters. Can be set within each configuration or set as a global default with an environment variable/top-level variable.
Custom Image with environment variables:
`TF_VAR_ba_pg_image` - Biganimal postgres image if not defined within the yaml configuration
`TF_VAR_ba_proxy_image` - Biganimal proxy image if not defined within the yaml configuration
`TF_VAR_ba_ignore_image` - Ignore image values (Default: false)
Configuration:
```yaml
aws:
biganimal:
example_cluster:
image:
pg: "example_one"
proxy: "example_two"
data_groups: ...
```
=> PLAT-65 - Biganimal custom images

edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf
Fixes: https://github.com/EnterpriseDB/edb-terraform/pull/200
=> FIX - omit Biganima custom images when both values are null and/or empty strings

edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf
pgpass requies escaping of colon (`:`) and backslash (`\`) characters with a backslash (`\`).
ref docs: https://www.postgresql.org/docs/current/libpq-pgpass.html
=> Biganimal module - remove colon from `random_password`

edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf
terraform's json encoding/decoding may change the representation of characters. ex: '<' => '\u003'
Ref: https://discuss.hashicorp.com/t/password-generated-has-unicode-in-it-in-terraform-state-file/51630
Ref: https://github.com/EnterpriseDB/edb-terraform/pull/211
=> Biganimal module - remove `<>&` from `random_password`

docs/examples/aws/biganimal.yml, docs/examples/azure/biganimal.yml, docs/examples/gcloud/biganimal.yml, edbterraform/__init__.py, edbterraform/data/terraform/biganimal/modules/biganimal/main.tf, edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf
Changes:
- Handle postgres engine abbreviations
- `postgres` = `pg`
- `pgextended` = `pge` 
- Allow terraform destruction to continue if the biganimal cluster was already destroyed or does not exist.
=> Handle Biganimal alt postgres engine names

edbterraform/__init__.py, edbterraform/data/terraform/biganimal/modules/biganimal/main.tf, edbterraform/data/terraform/biganimal/modules/biganimal/variables.tf
Fixes:
- biganimal module
- handle premium storage `azure` prefix for biganimal azure
- check for duplicate clusters instead of waiting for the api name constraint error
- delete leftover clusters after internal server failures
- Error:
```terraform
│ ERROR: curl: (22) The requested URL returned error: 500
│ {"error":{"status":500,"message":"Internal Server
│ Error","errors":[{"message":"failed to insert tags linked to the resource
│ p-r5xhp7i38n, reason: failed to create tags prior to linking them with the
│ resource p-r5xhp7i38n: failed to create tag: tag name
│ run_set_id:20241122112556347 already
│ exist"}],"reference":"upmrid/-oMzKhBF4QYPhyNVLy_Yr/2b6frNEA0I-EqYtfbVwfH","source":"mSvc"}}
```
- do not interpret special characters
- Error:
```terraform
│ Phase: parse error: Invalid …
```
=> PLAT-459 - Biganimal fixes

edbterraform/__init__.py, edbterraform/data/templates/aws/kubernetes.tf.j2, edbterraform/data/templates/azure/kubernetes.tf.j2, edbterraform/data/templates/gcloud/kubernetes.tf.j2, edbterraform/data/terraform/aws/modules/kubernetes/main.tf, edbterraform/data/terraform/aws/modules/kubernetes/outputs.tf, edbterraform/data/terraform/aws/modules/kubernetes/variables.tf, edbterraform/data/terraform/aws/modules/specification/main.tf, edbterraform/data/terraform/aws/modules/specification/outputs.tf, edbterraform/data/terraform/aws/modules/specification/variables.tf, edbterraform/data/terraform/azure/modules/kubernetes/main.tf, edbterraform/data/terraform/azure/modules/kubernetes/variables.tf, edbterraform/data/terraform/azure/modules/specification/main.tf, edbterraform/data/terraform/azure/modules/specification/outputs.tf, edbterraform/data/terraform/azure/modules/specification/variables.tf, edbterraform/data/terraform/common_vars.tf, edbterraform/data/terraform/gcloud/modules/kubernetes/main.tf, edbterraform/data/terraform/gcloud/modules/kubernetes/variables.tf, edbterraform/data/terraform/gcloud/modules/specification/main.tf, edbterraform/data/terraform/gcloud/modules/specification/outputs.tf, edbterraform/data/terraform/gcloud/modules/specification/variables.tf, edbterraform/lib.py
Changes:
- AWS Kubernetes (EKS)
- outputs added, any unformatted outputs are subject to change, modification or removal by the api or between releases
- `cluster_info`
- `cluster_auth`
- `raw`
- `force_service_kubernetes` root module variable added to add host public access list
- when no service cidrs are provided, public access is disabled to avoid exposing resources to `0.0.0.0/0`
- Azure Kubernetes
- `cluster_version` added to spec configuration
- Gcloud Kubernetes
- `cluster_version` added to spec configuration
Fixes:
- AWS Kubernetes (EKS)
- update EKS and VPC module versions
- remove unused Kubernetes provider list
- reference cluster name instead of cluster id
- use keyname and hex id for resource names
- tag resources
- `disable_eks_public_access` root module variable added as a …
=> PLAT-460 - AWS EKS fixes
